author: Jop Vernooij, Jeff Alexander
description: Get push notifications from your Minecraft server via Pushover.
main: net.jopv.minecraft.bukkit.minecraftpush.MinecraftPush
name: MinecraftPush
version: 1.3
api-version: 1.14
permissions:
    minecraftpush.receive:
        description: Can player receive notifications.
        default: true
    minecraftpush.broadcast:
        description: Can player broadcast.
        default: op
    minecraftpush.warnops:
        description: Can player warn operators.
        default: notop
commands:
    pushover:
        description: Enable or disable notifications for yourself.
        usage: /pushover <enable/disable> <pushover user key> ยง7(Get your user key by going to https://www.pushover.net/, logging in, copying it, and pasting it here.)
        aliases:
            - notifications
    broadcast:
        description: Broadcast to all online players, and to all offline players with notifications enabled.
        usage: /broadcast <message>
    warnops:
        description: Warn operators about something.
        usage: /warnops <message>
    minecraftpush:
        description: Copyright, source code, and donation information of MinecraftPush.
        usage: /minecraftpush
